# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - name: working-dir
    value: 'sistrado-backooffice/'

trigger:
  branches:
    include:
      - master
      - develop
      - feat/*
  paths:
    include:
      - 'sistrado-backooffice/*'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  inputs:
    containerRegistry: 'dockerRegistry'
    repository: 'sistrado-backoffice'
    command: 'buildAndPush'
    Dockerfile: $(working-dir)/Dockerfile
    tags: 'latest'
  displayName: 'Build and push'