# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - name: working-dir
    value: 'sistrado-backooffice/'

trigger:
  branches:
    include:
      - master
      - develop
      - feat/*
  paths:
    include:
      - 'sistrado-backooffice/*'

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
- task: Npm@1  
  displayName: 'Angular CLI'  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'install @angular/cli@11.0.7' 
- task: Npm@1  
  displayName: 'npm install'  
  inputs:  
    verbose: false 

- task: Npm@1  
  workingDirectory: $(working-dir)
  displayName: Build  
  inputs:  
    command: custom  
    verbose: false  
    customCommand: 'run build' 

- task: CopyPublishBuildArtifacts@1  
  workingDirectory: $(working-dir)
  inputs:  
    CopyRoot: dist  
    Contents: '**'  
    ArtifactName: backoffice  
    ArtifactType: Container  
  
- task: DownloadPipelineArtifact@2  
  workingDirectory: $(working-dir)
  inputs:  
    targetPath: ' $(Build.ArtifactStagingDirectory)/dist/app'  
