# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  - name: working-dir
    value: 'sistrado-app/'
  - name: 'imageName'
    value: 'sistrado_app'

trigger:
  branches:
    include:
      - master
      - develop
      - feat/*
  paths:
    include:
      - 'sistrado-app/*'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: Docker@2
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: $(working-dir)/Dockerfile
  displayName: Build an image